name: Trigger auto deployment for container-app-q2ipjjus3vt5g

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-q2ipjjus3vt5g-AutoDeployTrigger-8f2e1c7b-910f-4e33-96a9-7a0d89426751.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPQ2IPJJUS3VT5G_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPQ2IPJJUS3VT5G_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPQ2IPJJUS3VT5G_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryq2ipjjus3vt5g.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPQ2IPJJUS3VT5G_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPQ2IPJJUS3VT5G_REGISTRY_PASSWORD }}
          containerAppName: container-app-q2ipjjus3vt5g
          resourceGroup: reactbasic8530
          imageToBuild: containerregistryq2ipjjus3vt5g.azurecr.io/container-app-q2ipjjus3vt5g:${{ github.sha }}
          


